steps:
- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -xe;
    cd /workspace/{{ working_dir }} ;
    gcloud container clusters get-credentials --region={{ gke_cluster_region }} {{ gke_cluster_name }};
    skaffold run -f={{ skaffold_path }}  --default-repo=gcr.io/$PROJECT_ID;
