{{- if .Values.service }}
{{- if .Values.virtualService }}
{{- if .Values.virtualService.prefix }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.applicationName }}-virtualservice
spec:
  hosts:
    {{- range .Values.domains }}
    - {{ .name }} 
    {{- end }}
  gateways:
  - istio-system/{{ .Values.projectName | lower }}-httpbin-gateway
  http:
  - name: {{ .Values.applicationName }}-route
    match:
    - uri:
        prefix: {{ .Values.virtualService.prefix }}
    {{- if .Values.virtualService.rewrite.enabled }}
    rewrite:
      uri: {{ .Values.virtualService.rewrite.value }}
    {{- end }}
    route:
    - destination:
        host: {{ .Values.applicationName }}.{{ .Values.applicationName }}.svc.cluster.local
        port:
          {{- with (first .Values.ports) }}
          number: {{ .containerPort }}
          {{- end }}
    {{- if eq .Values.istioInjection "enabled"}}
    corsPolicy:
      allowHeaders:
      - sec-ch-ua
      - sec-ch-ua-mobile
      - sec-ch-ua-platform
      - access-control-allow-origin
      - grpc-timeout
      - keep-alive
      - content-type
      - content-transfer-encoding
      - custom-header-1
      - x-accept-content-transfer-encoding
      - x-accept-response-streaming
      - x-user-agent
      - x-grpc-web
      - authorization
      - request
      - authority
      - pragma
      - cache-control
      - accept
      - access-control-request-method
      - access-control-request-headers
      - origin
      - user-agent
      - sec-fetch-mode
      - sec-fetch-site
      - sec-fetch-dest
      - referer
      - accept-language
      allowMethods:
      - POST
      - GET
      - OPTIONS
      - PUT
      - DELETE
      allowOrigins:
      - regex: .*
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
