apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    projectName: {{ .Values.deploymentName }}
    environment: {{ .Values.environment }}
    type: namespace
    istio-injection: {{ .Values.istioInjection | quote }} 
