{{- if .Values.managedCertificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.projectName | lower }}-certificate
  namespace: istio-system
spec:
  secretName: {{ .Values.projectName | lower }}-certificate-secret
  dnsNames:
  {{- range .Values.domains }}
  - {{ .name }} 
  {{- end }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt
{{- end }}