{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.deploymentName }}-secret-env
  namespace: {{ $.Values.deploymentName }}
type: opaque
data:
  {{- range $key,$val := .Values.secrets }}
  {{$key}}: {{$val | b64enc}}
  {{- end}}
{{- end}}  