{{- if .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.deploymentName }}-sa@{{.Values.cloudProject}}.iam.gserviceaccount.com
  name: {{ .Values.deploymentName }}-ksa
  namespace: {{ .Values.deploymentName }}
{{- end }}
