author: CloudCover
category: containerise
description: This plugin only use to Run docker compose to build. Service name must define in docker compose yaml.
displayName: Docker Compose Build docker images
inputs:
    internal:
        - container_repository
        - container_tag
        - working_dir
    properties:
        docker_compose_service_name:
            description: |-
                Service Name which need to build
                 ,Note: Make sure Service name  must pe present in docker-compose.yaml
            title: Service Name
            type: string
        enable_docker_buildkit:
            default: true
            description: This input enable DOCKER_BUILDKIT
            title: Enable docker  build kit
            type: boolean
    required:
        - docker_compose_service_name
keywords:
    - Docker
    - Build
    - Push
    - Docker-compose
meta: {}
name: docker-compose-build
revision: 1
targets:
    - integration
version: 1
