{{- if .Values.managedCertificate }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
  name: {{ .Values.projectName | lower }}-httpbin-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    {{- range .Values.domains }}
    - {{ .name }} 
    {{- end }}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    {{- range .Values.domains }}
    - {{ .name }} 
    {{- end }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.projectName | lower }}-certificate-secret
      mode: SIMPLE
{{ else }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.projectName | lower }}-httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{- end}}

