provisioner: gcp
name: docker-compose-build-n-push
version: 1
revision: 1
displayName: Docker Compose Build & Push docker images
description: This plugin only use to Run docker compose to   build  & push docker image for specific service with  tag git Hash Commit or any Container tag. Service name must define in docker compose yaml.
target: ""
category: containerise
keywords:
  - Docker
  - Build
  - Push 
  - Docker-compose
    
author: CloudCover
meta: {}
inputs:
  properties:
    docker_compose_service_name:
      title: Service Name
      description: "Service Name for which Docker image will build & push \n ,Note: Make sure Service name  must pe present in docker-compose.yaml"
      type: string
    enable_docker_buildkit:
      title: Enable docker  build kit
      description: This input enable DOCKER_BUILDKIT
      type: boolean
      default: true    
    container_repository:
      title: Container repository
      description: Complete repository path
      type: string           
    container_tag:
      title: Image Tag
      description: Tag name for the container image
      type: string
      default: ""      
    use_github_tag:
      title: Use github tag
      description: true value will push the image reference with git commit sha tag as well
      type: boolean
      default: true
    working_dir:
      title: Working directory
      description: The current working directory to execute command
      type: string
      default: repo
    sha_tag:
      title: SHA Git commit tag
      description: Resloved Commit hash for Input git artifact
      type: string     
     
  required:
    - docker_compose_service_name
  internal:
    - sha_tag    
    - container_repository
    - container_tag    
template: |
  steps:
  - id: 'Docker login'
    name: 'gcr.io/cloud-builders/docker'
    dir: {{ working_dir }}
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo $$docker_password | docker login -u $$docker_username --password-stdin $$docker_registry
    
  - id: 'Docker Compose Build image'
    name: 'gcr.io/cloud-builders/docker'
    dir: {{ working_dir }}
    entrypoint: 'bash'  
    args:
    - '-c'
    - |  
      docker compose build {{ docker_compose_service_name }}
    env:
    {% if enable_docker_buildkit == true %}      
      - "DOCKER_BUILDKIT=1"
    {% endif %}
  
  - id: 'Docker Compose Push image'
    name: 'gcr.io/cloud-builders/docker'
    dir: {{ working_dir }}
    entrypoint: 'bash'  
    args:
    - '-c' 
    - |  
      {% verbatim %}export image_name=$(docker image ls --format "table {{.Repository}}:{{.Tag}}"|head -2 | tail -1){% endverbatim %}      
      echo Docker compose created the image: $image_name ......
      docker tag $image_name {{container_repository}}:{{container_tag}}
      docker push {{container_repository}}:{{container_tag}}
      {% if use_github_tag == true %}
      docker tag $image_name {{container_repository}}:{{ sha_tag }}
      docker push {{container_repository}}:{{ sha_tag }}  
      {% endif %}  



