provisioner: azure
name: pipeline-config
version: 1
revision: 1
displayName: Configure Pipeline
description: Configure global pipeline options and environment.
target: config
keywords:
  - env
  - environment
  - secret
  - config
  - configuration
author: Ollion
meta: {}
inputs:
  properties:
    variable_group_name:
      title: Secret Variables Group
      description: Keeps all secret variables available to pipeline.
      type: string
      default: ""
    pool_name:
      title: Pool Name
      description: Use selfhosted agent by proving agent pool name.
      type: string
      default: ""
  required:
    - variable_group_name
  internal:
    - variable_group_name
template: |
  pool:
  {% if pool_name %}
    name: {{ pool_name }}
  {% else %}
    vmImage: ubuntu-latest
  {% endif %}
  name: '$(Date:yyyyMMdd)$(Rev:.r)'
  variables:
    - group: {{ variable_group_name }}
