{{- range  $index,$artifact := .Values.artifacts }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.applicationName }}-secret-{{$index}}
  namespace: {{ $.Values.applicationName }}
type: generic
data:
{{- $files := $.Files }}
  {{- range $artifact.files}}
  {{ . }}: |-
    {{ $files.Get . | b64enc }}
  {{- end}}
{{- end}}
