{{- if .Values.ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.deploymentName }}
  labels:
    projectName: {{ .Values.deploymentName }}
    environment: {{ .Values.environment }}
    type: service
spec:
  type:  LoadBalancer
  ports:
  {{- range  $port := $.Values.ports }}
    - name: {{$port.name}}
      targetPort: {{$port.containerPort}}
      port: {{$port.containerPort}}
      protocol: {{$port.protocol}}
  {{- end}}
  selector:
    projectName: {{ .Values.deploymentName }}
    environment: {{ .Values.environment }}
    type: deployment
{{- end}}