---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.deploymentName }}
  labels:
    projectName: {{ .Values.deploymentName }}
    environment: {{ .Values.environment }}
    type: deployment
spec:
  selector:
    matchLabels:
      projectName: {{ .Values.deploymentName }}
      environment: {{ .Values.environment }}
      type: deployment
  strategy:
    type: {{ .Values.deploy.strategy }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deploy.maxUnavail }}
      maxSurge: {{ .Values.deploy.maxSurge }}
  template:
    metadata:
      labels:
        projectName: {{ .Values.deploymentName }}
        environment: {{ .Values.environment }}
        type: deployment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: project
                  operator: In
                  values:
                  - {{ .Values.deploymentName }}
                - key: env
                  operator: In
                  values:
                  - {{ .Values.environment }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      {{- if .Values.image.registryCredentials }}
      imagePullSecrets:
        - name: {{ .Values.deploymentName }}-docker-registry
      {{- end }}
      containers:
        - name: {{ .Values.deploymentName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range  $port := .Values.ports }}
            - name: {{$port.name}}
              containerPort: {{$port.containerPort}}
              protocol: {{$port.protocol}}
          {{- end}}
          livenessProbe:
          {{- range  $index,$port := .Values.ports }}
            {{- if eq $index  0}}
            tcpSocket:
              port: {{$port.containerPort}}
            {{- end}}
          {{- end}}
            failureThreshold: {{ .Values.deploy.healthCheck.liveFailThreshold }}
            successThreshold: {{ .Values.deploy.healthCheck.liveSuccThreshold }}
            initialDelaySeconds: {{ .Values.deploy.healthCheck.delay }}
            periodSeconds: {{ .Values.deploy.healthCheck.period }}
            timeoutSeconds: {{ .Values.deploy.healthCheck.timeout }}
          readinessProbe:
            {{- range  $index,$port := .Values.ports }}
            {{- if eq $index  0}}
            {{ if $port.healthcheck }}
            httpGet:
              path: {{$port.healthcheck}}
              port: {{$port.containerPort}}
            {{- else -}}
            tcpSocket:
              port:  {{$port.containerPort}}
            {{- end}}
            {{- end}}
            {{- end}}
            failureThreshold: {{ .Values.deploy.healthCheck.readFailThreshold }}
            successThreshold: {{ .Values.deploy.healthCheck.readSuccThreshold }}
            initialDelaySeconds: {{ .Values.deploy.healthCheck.delay }}
            periodSeconds: {{ .Values.deploy.healthCheck.period }}
            timeoutSeconds: {{ .Values.deploy.healthCheck.timeout }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.deploymentName }}-configmap
            {{- if .Values.secrets }}
            - secretRef:
                name: {{ $.Values.deploymentName }}-secret-env
            {{- end}}  
          volumeMounts:
          {{- range  $index,$artifact := .Values.artifacts }}
            - name: {{ $.Values.deploymentName }}-volume-{{$index}}
              mountPath: {{ $artifact.mountPath }}
          {{- end}}
        {{- if  .Values.lifecycle.prestop.command }}        
          lifecycle:
            preStop:
              exec:
                command: {{ .Values.lifecycle.prestop.command }}
        {{- end }}
      serviceAccount: {{ .Values.deploymentName }}-ksa
      serviceAccountName: {{ .Values.deploymentName }}-ksa
      terminationGracePeriodSeconds: {{ .Values.deploy.terminationGracePeriodSeconds }}
      volumes:
        {{- range  $index,$artifact := .Values.artifacts }}
        - name: {{ $.Values.deploymentName }}-volume-{{$index}}
          secret:
            secretName: {{ $.Values.deploymentName }}-secret-{{$index}}
        {{- end}}
        