{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.applicationName }}-ingress
  namespace: {{ .Values.applicationName }}
  annotations:
  {{- if .Values.service.private}}
    kubernetes.io/ingress.class: "gce-internal"
  {{- end}}
spec:
{{- $len := len .Values.ports }}
{{- if eq $len 1 }}
  backend:
    serviceName: {{ .Values.applicationName }}
    {{- range  $index,$port := .Values.ports }}
    {{- if eq $index  0}}
    servicePort: {{$port.name}}
    {{- end}}
    {{- end}}
{{- else}}
  rules:
  - http:
      paths:
      {{- range $index,$port := .Values.ports }}
      - path: /{{$port.name}}/*
        pathType: Prefix 
        backend:
          service:
            name: {{ $.Values.applicationName }}
            port: 
              number: {{ $port.name}}
      {{- end}}
{{- end }}
