{{- if .Values.image.registryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationName }}-docker-registry
  namespace: {{ .Values.applicationName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imageRegistryCredentials" . }}
{{- end }}