name: $(Build.DefinitionName)_${{ replace(replace(variables['Build.SourceBranch'],'refs/heads/',''),'/','_') }}_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - refs/tags/int-*
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: ollionorg/product-build-tools
      endpoint: Github-CldCvr

pool:
  vmImage: ubuntu-latest

variables:
  - group: Common-Dev
  - group: CodePipes-Int-Prod-DB

steps:
  - template: templates/run-db-update.yml@templates
    parameters:
      gcpSACreds: $(GCP_SA_CREDS)
      DBInstanceConnectionName: $(DB_INSTANCE_CONNECTION_NAME)
