apiVersion: v1
kind: Service
metadata:
  annotations:
      cloud.google.com/neg: '{"ingress": true}' 
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.applicationName }}
  labels:
    projectName: {{ .Values.applicationName }}
    environment: {{ .Values.environment }}
    type: service
spec:
  type:  NodePort
  ports: 
  {{- range  $port := .Values.ports }}
    - name: {{$port.name}}
      targetPort: {{$port.containerPort}}
      port: {{$port.containerPort}}
      protocol: {{$port.protocol}}
  {{- end}}
  selector:
    projectName: {{ .Values.applicationName }}
    environment: {{ .Values.environment }}
    type: deployment